name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and run PyInstaller
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          pyinstaller --onefile --windowed --add-data format.properties;. --name frecri main.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: frecri-win-zip
          path: dist/frecri-win.zip

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Windows Build
          files: dist/frecri.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}