name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and run PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pyinstaller --onefile --windowed --add-data format.propierties;. main.py

    
      - name: Check PyInstaller installation
        run: python -m pip show pyinstaller

      - name: List files (debug)
        run: dir

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: frecri-exe
          path: dist/frecri.exe